name: Python Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Echo
        run: |
          echo ${{ vars.TOKEN }} >> test.txt
      - name: Cat
        run: cat test.txt
